hotel/cart/urls.py
from django.contrib import admin
from django.urls import path
from cart import views
app_name='cart'

urlpatterns = [
    path('cart_view/', views.cart_view, name='cart_view'),
path('addtocart/<int:p>', views.addtocart, name='addtocart'),
path('orderform/', views.placeorder, name='placeorder'),
path('orderview', views.orderview, name="orderview"),
path('pickup/', views.pickup, name='pickup'),
path('cart_remove/<int:p>', views.cart_remove, name="cart_remove"),
path('full_remove/<int:p>', views.full_remove, name="full_remove"),
]

hotel/hotel/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("resto.urls")),
    path('search',include("search.urls")),
path('cart',include("cart.urls"))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hotel/resto/urls.py
from django.contrib import admin
from django.urls import path
from resto import views
app_name='resto'

urlpatterns = [
    path('',views.allproducts,name='allproducts'),
    path('viewproducts/<slug:cslug>',views.viewproducts,name='viewproducts'),
path('prodetail/<slug:pslug>',views.prodetail,name='prodetail'),
path('login',views.user_login,name='login'),
path('logout',views.user_logout,name='logout'),
path('register',views.register,name='register'),
path('customer',views.customer,name='customer'),
]

hotel/search/urls.py
from django.contrib import admin
from django.urls import path
from search import views
app_name="search"

urlpatterns = [
    path('search',views.searchresult,name='searchresult'),


]

hotel/cart/models.py
from django.db import models
from resto.models import Product
from django.contrib.auth.models import User
from datetime import datetime
class Cart(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    products=models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    date_added=models.DateTimeField(auto_now_add=True)
    active=models.BooleanField(default=True)
    def subtotal(self):
        return self.quantity*self.products.price
    def __str__(self):
        return self.products.name
class Account(models.Model):
    acctnumber=models.CharField(max_length=200)
    accttype=models.CharField(max_length=30)
    amount=models.IntegerField()
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    def __str__(self):
        return self.acctnumber
class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    products = models.ForeignKey(Product, on_delete=models.CASCADE)
    address = models.TextField()
    phone = models.CharField(max_length=11)
    order_status = models.CharField(max_length=30, default="pending")
    delivery_status = models.CharField(max_length=30, default="pending")
    noofitems = models.IntegerField()
    date_added = models.DateTimeField(auto_now_add=True)
    pickup_time=models.CharField(max_length=6)
    pickup_status = models.CharField(max_length=30, default="pending")
    pickup_date=models.DateTimeField(default=datetime(2023, 6, 30, 22, 30, 0))
    def __str__(self):
        return self.user.username

    def subtotal1(self):
        return self.noofitems*self.products.price

hotel/search/models.py
from django.db import models

# Create your models here.

hotel/cart/views.py
from django.shortcuts import render,redirect
from cart.models import Cart,Account,Order
from resto.models import Product
from django.contrib.auth.decorators import login_required

def cart_view(request):
    total=0
    try:
        user=request.user
        cart=Cart.objects.filter(user=user)
        for i in cart:
            total+=i.quantity*i.products.price
    except Cart.DoesNotExist:
        pass

    return render(request,'cart.html',{'cart':cart,'total':total})
@login_required
def addtocart(request,p):
    product=Product.objects.get(id=p)
    user=request.user
    try:
        cart=Cart.objects.get(products=product,user=user)
        if cart.quantity<cart.products.stock:
            cart.quantity+=1
        cart.save()
    except:
            cart=Cart.objects.create(products=product,user=user,quantity=1)
            cart.save()
    return redirect('cart:cart_view')
@login_required
def placeorder(request):

    total=0
    items=0
    if(request.method=="POST"):
        ad = request.POST['ad']
        p = request.POST['p']
        num = request.POST['num']
        user=request.user
        cart=Cart.objects.filter(user=user)
        for i in cart:
            total+=i.quantity*i.products.price
            items+=i.quantity
        ac=Account.objects.get(acctnumber=num)
        if float(ac.amount)>=total:
            ac.amount=ac.amount-total
            ac.save()
            for i in cart:
                o=Order.objects.create(user=user,products=i.products,address=ad,phone=p,order_status="paid",noofitems=i.quantity)
                o.save()
            cart.delete()
            msg="Ordered Placed successfully"
            return render(request,'orderdetail.html',{'msg':msg,'total':total,'items':items})
        else:
            msg="insufficiant Amount..please add money"
            return render(request,'orderdetail.html',{'msg':msg})
    return render(request,'orderform.html')
@login_required
def orderview(request):
    user=request.user
    cart = Cart.objects.filter(user=user)
    o = Order.objects.filter(user=user, order_status="paid")
    return render(request,'orderview.html',{'o':o,'name':user.username})


@login_required
def pickup(request):
    total = 0
    items = 0
    if (request.method == "POST"):
        ad = request.POST['ad']
        p = request.POST['p']
        num = request.POST['num']
        ti=request.POST['ti']
        di = request.POST['di']
        user = request.user
        cart = Cart.objects.filter(user=user)
        for i in cart:
            total += i.quantity * i.products.price
            items += i.quantity
        ac = Account.objects.get(acctnumber=num)
        if float(ac.amount) >= total:
            ac.amount = ac.amount - total
            ac.save()
            for i in cart:
                o = Order.objects.create(user=user, products=i.products, address=ad, phone=p,pickup_time=ti,pickup_date=di, order_status="paid",
                                         noofitems=i.quantity)
                o.save()
            cart.delete()
            msg = "Ordered Placed successfully"
            return render(request, 'orderdetail.html', {'msg': msg, 'total': total, 'items': items})
        else:
            msg = "insufficiant Amount..please add money"
            return render(request, 'orderdetail.html', {'msg': msg})

    return render(request,'pickup.html')
@login_required
def cart_remove(request,p):
    user=request.user
    product=Product.objects.get(id=p)
    try:
        cart=Cart.objects.get(user=user,products=product)
        if cart.quantity>1:
            cart.quantity -= 1

        else:
            cart.delete()
        cart.save()
    except:
         pass
    return redirect('cart:cart_view')
def full_remove(request,p):
    user=request.user
    product=Product.objects.get(id=p)
    try:
        cart=Cart.objects.get(user=user,products=product)
        cart.delete()

    except:
        pass
    return redirect('cart:cart_view')

hotel/search/views.py
from django.shortcuts import render
from django.db.models import Q
from resto.models import Product

def searchresult(request):
    products=None
    if request.method=='POST':
        query=""
        query=request.POST.get('q')
        if query:
            products=Product.objects.filter(Q(name__icontains=query)|Q(desc__icontains=query));
        return render(request,'search.html',{'query':query,'p':products})

hotel/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
  <link rel="stylesheet" href="{% static 'img/bg.jpg' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</head>

<body id="background" style="background-image:url('{% static 'img/bg.jpg'%}');">
 <header style="background-color:black;">
   <center><img src="{% static 'img/logo.jpg' %}" style="height:120px;width:120px;margin-right:1390px;">
    <div class="container text-center" style="margin-top:-110px;">
      <small style="color:orange;font-size:50px;">HALF TIME GRILL HOUSE</small> <br>
      <small style="color:white;font-size:20px;">Vadakkethara,Pazhayannur,Thrissur</small><br>
<small style="font-size:20px;color:white;">828 110 499/ 828 110 599</small>

    </div></header>
<nav class="navbar navbar-expand-lg bg-dark ">
  <a class="navbar-brand" href="#">HALF TIME</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'resto:allproducts' %}">Home <span class="sr-only"></span></a>
      </li>
        <li class="nav-item dropdown" style="font-weight:bold;color:black;">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Shop
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'resto:allproducts' %}">All Categories</a></li>
            {% for i in links %}
              <li><a class="dropdown-item" href="{% url 'resto:viewproducts' i.slug %}">{{i.name}}</a></li>
            {% endfor %}
          </ul></li>
      {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'resto:logout' %}">logout</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'cart:cart_view' %}"><i class="fa-solid fa-cart-shopping"></i>{{item_count}}</a>
        </li>
               <li class="nav-item">
          <a class="nav-link" href="{% url 'cart:orderview' %}">Your Orders</a>
        </li>


        {% else %}
            <li class="nav-item">
          <a class="nav-link" href="{% url 'resto:login' %}">login</a>
        </li>

          <li class="nav-item">
          <a class="nav-link" href="{% url 'resto:register' %}">Register</a>
        </li>

        {% endif %}



    </ul>
      <div2>
    <form class="d-flex" action="{% url 'search:searchresult' %}" method="POST">
      {% csrf_token %}
      <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form></div2>
  </div>
</nav>
{% block content %}
{% endblock %}



<br><br>
<footer class="footer" style="position:relative;margin-top:300px;">

         <img src="{% static 'img/logo.jpg' %}" style="height:120px;width:120px;margin-right:100px;">
                 <img src="{% static 'img/delivery.png' %}" style="height:50px;width:120px;margin-left:280px;margin-bottom:-100px;">

    <div class="container text-center" style="margin-top:-110px;">
      <small style="color:orange;font-size:40px;">HALF TIME GRILL HOUSE</small><br>
      <small>Vadakkethara,Pazhayannur,Thrissur</small><br>
<small style="font-size:20px;">828 110 499/ 828 110 599</small>
    </div>

  </footer>


</body>
</html>

hotel/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<table class="table table-bordered" style="background-color:black;">
    <tr style="color:white;"><th>Your Items</th>
    <td style="color:white; font-weight:bold;">Product name</td>
    <td style="color:white; font-weight:bold;">Price</td>
    <td style="color:white; font-weight:bold;">Total</td></tr>
    {% for i in cart %}
    <tr style="color:white;">
        <td>
        <img src="{{i.products.img.url}}" style="height:150px;width:150px;"></td>
        <td>{{i.products.name}}</td>
        <td>unit price:{{i.products.price}}
        quantity:{{i.quantity}}</td>
        <td style="font-weight:bold;font-size:30px;">{{i.subtotal}}</td>
         <td>Subtotal:{{i.subtotal}}</td>
                    {% if i.quantity < i.products.stock %}
                    <td><a href="{% url 'cart:addtocart' i.products.id %}"><i class="fa-solid fa-plus"></i></a>
                        <a href="{% url 'cart:cart_remove' i.products.id %}"><i class="fa-solid fa-minus"></i></a>
                        <a href="{% url 'cart:full_remove' i.products.id %}"><i class="fa-solid fa-trash"></i></a></td>
                    {% else %}
                    <td> <a href="{% url 'cart:cart_remove' i.products.id %}"><i class="fa-solid fa-minus"></i></a>
                        <a href="{% url 'cart:full_remove' i.products.id %}"><i class="fa-solid fa-trash"></i></a></td>
                    {% endif %}
    </tr>
    {% endfor %}
</table>
<div>
    <table class="table table bordered" style="padding:10px 20px;">
        <th colspan="5" style="font-weight:bold;color:white;"> checkout</th>
        <tr style="font-weight:bold;color:white;"> <th>total:&nbsp;{{total}} rupees</th></tr>

    </table>
    <a href="{% url 'cart:placeorder' %}" class="btn btn-primary">placeorder</a>
     <a href="{% url 'cart:pickup' %}" class="btn btn-primary">Pickup</a>
</div>

{% endblock %}

hotel/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="respo" style="color:yellow;">
<div id="mycarousel" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-90" style="height:300px;width:1000px;margin-left:150px;" src="{% static 'img/fried2.jpg' %}" alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-90" style="height:300px;width:1000px;margin-left:150px;" src="{% static 'img/burger.jpg' %}" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-90" style="height:300px;width:1000px;margin-left:150px;" src="{% static 'img/fried3.jpg' %}" alt="Second slide">
    </div>

  </div>
    <a class="carousel-control-prev" href="#mycarousel" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#mycarousel" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<div class="container mt-3 " id="ca![](../../../../AppData/Local/Temp/fried2.jpg)rds" style="margin-bottom:100px;justify-content: space-around;">
  <div class="row mx-auto">
{% for i in c %}

    <div3 class="col-sm-3 mt-3">
<div class="card" style="height:260px;width:180px;">
  <img src="{{i.img.url}}" class="card-img-top" style="height:100px;width:100%;" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title" style="font-size:18px;">{{i.name}}</h5>
    <p class="card-text">{{i.desc}}</p>
    <a href="{% url 'resto:viewproducts' i.slug %}"  class="btn btn-primary">know more</a>
  </div>
</div>
    </div3>
{% endfor %}
  </div>
</div>
</div>
{% endblock %}

hotel/templates/customer.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{{a.amount}}
{% endblock %}

hotel/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-3">
            <img src="{{p.img.url}}" style="height:280px;width:360px;" alt="{{p.img.url}}">
        </div>
        <div class="col-sm-10">
            <div>
                <h1 style="color:red">{{p.name}}  </h1>
                <p style="font-weight:bold;color:white;font-size:2rem;">{{p.price}} </p>
<a class="btn btn-primary" href="{% url 'cart:addtocart' p.id %}">addtocart</a>

            </div>
        </div>
    </div>
</div>
<div class="container mt-3 " id="ca![](../../../../AppData/Local/Temp/fried2.jpg)rds" style="margin-bottom:100px;justify-content: space-around;">
  <div class="row mx-auto">
{% for i in c %}

    <div3 class="col-sm-3 mt-3">
<div class="card" style="height:260px;width:180px;">
  <img src="{{i.img.url}}" class="card-img-top" style="height:100px;width:100%;" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title" style="font-size:18px;">{{i.name}}</h5>
    <p class="card-text">{{i.desc}}</p>
    <a href="{% url 'resto:viewproducts' i.slug %}"  class="btn btn-primary">know more</a>
  </div>
</div>
    </div3>
{% endfor %}
  </div>
</div>
{% endblock %}

hotel/templates/login.html
{%extends 'base.html' %}
{% load static %}
{% block content %}
<div style="margin-left:200px;">
<h1 style="font-weight:bold;color:orange;">Login</h1>
<form method="post" style="width:300px;font-size:20px;color:black;">
  {% csrf_token %}
<div class="mb-3">
  <label class="form-label">Username</label>
  <input type="text" class="form-control" name="u" placeholder="enter a number">
</div>


   <div class="mb-3" >
  <label class="form-label">Password</label>
  <input type="password" class="form-control" name="p" placeholder="Enter Password">
</div>


      <div class="col-auto" >
         <button class="btn btn-outline-success my-2 my-sm-0" style="font-weight:bold;" type="submit">Login</button>
          <a href="{% url 'resto:register' %}" class="btn btn-outline-success my-2 my-sm-0">Sign Up</a>
      </div>


</form>
{% if messages %}
{% for i in messages %}
<ul class="messages">
    <li>{{i}}</li>
</ul>
{% endfor %}
{% endif %}
</div>
{% endblock %}

hotel/templates/orderdetail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container" style="margin-bottom:100px;color:white;font-size:60px;">
  <h1 style="color:red;font-size:100px;">Order Details..</h1>
  Total:{{total}}<br>
  Status:{{msg}}<br>
  Quantity:{{items}}<br>
  <p style="color:orange;font-size:30px;">Woohoo...<br>
Thank you for Your order! We know you're going to love it...
</p>
</div>

{% endblock %}

hotel/templates/orderform.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<form method="POST" style="width:12cm;padding:10px 20px;margin-top:10px;font-weight:bold;color:orange;">
  {% csrf_token %}
  <div class="form-group">
    <label>Address</label>
    <input type="text" class="form-control" name="ad" placeholder="Enter Address">
  </div>
  <div class="form-group">
    <label>Phone Number</label>
    <input type="number" class="form-control" name="p" placeholder="Phone number">
  </div>
  <div class="form-group">
    <label>Account Number</label>
    <input type="number" class="form-control" name="num" placeholder="Account Number">
  </div><br>

  <input type="submit" class="btn btn-primary" style="position:center;" >
</form>
{% endblock %}

hotel/templates/orderview.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
customer:{{name}}
<table class="table table-bordered" style="background-color:black;">
  <tr style="color:green;font-weight:bold;">
    <th>Products </th>
    <td>Name</td>
    <td>Qty/Price</td>
  <td>Address</td>
  <td>Amount</td>
    <td>Pickup_time</td>
  <td>Order status</td>
  </tr>
  {% for i in o %}
  <tr style="color:white"> <td><img src="{{i.products.img.url}}" style="height:150px;width:150px;"></td>

    <td>{{i.products.name}}</td>
    <td>{{i.noofitems}}<br>{{i.products.price}}</td>
    <td>{{i.address}}</td>
    <td>{{i.date_added}}<br>{{i.subtotal1}}<br>{{i.order_status}}</td>
    <td>{{i.pickup_time}}</td>

          <td style="color:red;">ph:{{i.phone}}<br>{{i.delivery_status}}</td>




  </tr>
{% endfor %}

</table>

{% endblock %}

hotel/templates/pickup.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<form method="POST" style="width:12cm;padding:10px 20px;margin-top:10px;font-weight:bold;color:orange;">
  {% csrf_token %}
  <div class="form-group">
    <label>Address</label>
    <input type="text" class="form-control" name="ad" placeholder="Enter Address">
  </div>
  <div class="form-group">
    <label>Phone Number</label>
    <input type="number" class="form-control" name="p" placeholder="Phone number">
  </div>
  <div class="form-group">
    <label>Account Number</label>
    <input type="number" class="form-control" name="num" placeholder="Account Number">
  </div>
  <div class="form-group">
    <label>Pickup_time</label>
    <input type="time" class="form-control" name="ti"  placeholder="pickup_time">
  </div>
  <div class="form-group">
    <label>Pickup_date</label>
    <input type="date" class="form-control" name="di"  placeholder="pickup_date">
  </div><br>

  <input type="submit" class="btn btn-primary">
</form>
{% endblock %}

hotel/templates/pickup_view.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
customer:{{name}}
<table class="table table-bordered" style="background-color:black;">
  <tr style="color:green;font-weight:bold;">
    <th>Products </th>
    <td>Name</td>
    <td>Qty/Price</td>
  <td>Address</td>
  <td>Amount</td>
  <td>Delivery status</td></tr>
  {% for i in o %}
  <tr style="color:white"> <td><img src="{{i.products.image.url}}" style="height:150px;width:150px;"></td>

    <td>{{i.products.name}}</td>
    <td>{{i.noofitems}}<br>{{i.products.price}}</td>
    <td>{{i.address}}</td>
    <td>{{i.date_added}}<br>{{i.subtotal1}}<br>{{i.order_status}}</td>
    <td style="color:red;">ph:{{i.phone}}<br>{{i.pickup_status}}</td>

  </tr>
{% endfor %}

</table>

{% endblock %}tml>

hotel/templates/products.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container mt-3 " id="cards" style="margin-bottom:100px;justify-content: space-around;">
  <div class="row mx-auto">
    {% for i in p %}
    <div class="col-sm-3">
      <div class="card" style="height:300px;width:180px;">
        <img src="{{i.img.url}}" class="card-img-top" style="height:100px;width:100%;" alt="Card image cap">
        <div class="card-body" style="justify-content: space-between;" >
          <h5 class="card-title" style="font-size:16px;">{{i.name}}</h5>
          <p class="card-text">{{i.desc}}<br>{{i.price}}</p>
          <a href="{% url 'resto:prodetail' i.slug %}" class="btn btn-primary" >Order</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>



{% endblock %}

hotel/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container" style="margin-bottom:100px">
<h1>signup</h1>
<form method="post" style="width:400px;">
    {% csrf_token %}
<div class="mb-3">
  <label class="form-label">username</label>
  <input type="text" class="form-control" name="u" placeholder="enter username">
</div>
    <div class="mb-3">
  <label class="form-label">firstname</label>
  <input type="text" class="form-control" name="f" placeholder="Enter firstname">
</div>
   <div class="mb-3">
  <label class="form-label">lastname</label>
  <input type="text" class="form-control" name="l" placeholder="Enter lastname">
</div>
   <div class="mb-3">
  <label class="form-label">email</label>
  <input type="email" class="form-control" name="e" placeholder="Enter email">
</div>
   <div class="mb-3">
  <label class="form-label">password</label>
  <input type="password" class="form-control" name="p" placeholder="Enter Password">
</div>
   <div class="mb-3">
  <label class="form-label">confirmpassword</label>
  <input type="password" class="form-control" name="cp" placeholder="Enter confirmpassord">
</div>
    <div class="col-auto">
        <button type="submit" class="btn btn-primary mb-3">submit</button>
    </div>
</form>
</div>
{% endblock %}

hotel/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
  <div>
    <h3>You have serached for {{query}}</h3>
  </div>
</center>
<div class="container mt-3 " id="cards" style="margin-bottom:100px;justify-content: space-around;">
  <div class="row">
    {% for i in p %}
    <div class="col-sm-3">
      <div class="card" style="height:400px;width:18rem;">
        <img src="{{i.img.url}}" class="card-img-top1"  alt="Card image cap">
        <div class="card-body"  >
          <h5 class="card-title">{{i.name}}</h5>
          <p class="card-text">{{i.desc}}</p><a href="{% url 'resto:prodetail' i.slug %}" class="btn btn-primary">know more</a>
        </div>
      </div>
    </div>
    {% empty %}
    <div><p>0 Result Found</p></div>
    {% endfor %}
  </div>
</div>
{% endblock %}